// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.28;

import {ModuleBase} from "../ModuleBase.sol";
import {Events} from "../../libraries/Events.sol";
import {IERC20} from "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import {SafeERC20} from "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";

/// @title OdosModule
/// @notice Swap module using Odos Aggregator (Arbitrum and other EVM chains)
/// @dev Stateless — executes via delegatecall from the vault.
///      The API generates Odos calldata off-chain and passes it in — identical
///      pattern to KodiakModule but for Odos instead of KXRouter.
contract OdosModule is ModuleBase {
    using SafeERC20 for IERC20;

    /// @notice Odos Router V2 — deployed at the same address on most EVM chains
    address public constant ODOS_ROUTER = 0xa669e7A0d4b3e4Fa48af2dE86BD4CD7126Be4e13;

    function moduleType() external pure override returns (bytes32) {
        return keccak256("swap.odos");
    }

    /// @notice Swap tokens via Odos Aggregator
    /// @param tokenIn     Token to swap from
    /// @param amountIn    Amount to swap (type(uint256).max = full vault balance)
    /// @param tokenOut    Token to receive
    /// @param minAmountOut Slippage protection — revert if received < this
    /// @param odosCalldata Pre-encoded calldata for the Odos router, generated by the API
    function swap(
        address tokenIn,
        uint256 amountIn,
        address tokenOut,
        uint256 minAmountOut,
        bytes calldata odosCalldata
    ) external payable onlyDelegatecall {
        uint256 amount = amountIn == type(uint256).max
            ? IERC20(tokenIn).balanceOf(address(this))
            : amountIn;
        if (amount == 0) revert Events.ZeroAmount();

        uint256 balanceBefore = IERC20(tokenOut).balanceOf(address(this));

        IERC20(tokenIn).forceApprove(ODOS_ROUTER, amount);
        (bool success, ) = ODOS_ROUTER.call(odosCalldata);
        if (!success) revert Events.OperationFailed();
        IERC20(tokenIn).forceApprove(ODOS_ROUTER, 0);

        uint256 received = IERC20(tokenOut).balanceOf(address(this)) - balanceBefore;
        if (received < minAmountOut) revert Events.InsufficientBalance();

        emit Events.Swapped(tokenIn, tokenOut, amount, received);
    }
}
